name: Release Notifications

on:
  release:
    types: [published, created]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: jeffersfp/github-release-slack-notification@v0.1.1
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          mentions: 'U1234567890,U0987654321'
